package dev.subashcodes.carrentalsystem.model;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Getter
@Setter
@Document
public class User {
    @Id //this tells this is the primary key of the collection, and it will be automatically generated by mongodb.
    private String userId;

    private String username;
    private String email;
    private String password;
    private String address;
    private String phone;
    private String role;
}
